title: BCP 101 - Summer 2026 - UC Davis
description: Computational pedagogy for educators
theme: just-the-docs

url: https://ngs-docs.github.io/2026-summer-bcp-101/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
